application: txtbranch
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest
  
handlers:
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /assets
  static_dir: assets
  
- url: /admin/.*
  script: admin.application
  login: admin

- url: /mock/.*
  script: mock.application
  login: admin

- url: /test.*
  script: gaeunit.application
  login: admin

- url: /api/v1/.*
  script: api.application

- url: /.*
  script: branch-engine.application
  
