application: txtbranch
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: django
  version: "1.4"
  
handlers:
  
- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico
  
- url: /config\.json
  static_files: config.json
  upload: config\.json
  
- url: /messages\.json
  static_files: messages.json
  upload: messages\.json
  
- url: /assets
  static_dir: assets
  
- url: /test.*
  script: gaeunit.application
  login: admin

- url: /api/v1/.*
  script: api.application

- url: /.*
  script: branch-engine.application
  
